# Generated by Django 4.1.5 on 2023-01-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_remove_customuser_age_customuser_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
